---
title: "KMR_QE_ProjectWriteUp"
author: "Kinsey Reed"
date: "4/5/2021"
output: html_document
---


Load in dataset


```{r}
data <- read.csv('2020_data.csv')
head(data)

```

For Mineralization/Immobilization
```{r}
#one-way farm
nm_fit1 <- lm(net_min ~ farm, data = data)

#two-way farm and incubation
nm_fit2 <- lm(net_min ~ incubation + farm, data = data)

#interaction
nm_fit <- lm(net_min ~ incubation * farm, data = data)
summary(nm_fit)

library(AICcmodavg)
model.set <- list(nm_fit1, nm_fit2, nm_fit)
model.names <- c("one", "two", "interaction")
aictab(model.set, modnames = model.names)
#interaction has lowest AIC score and is the best fit for the data.

#check for homoscedasticity
par(mfrow = c(2,2))
plot(nm_fit)
par(mfrow=c(1,1))

#anova test (should be same)
nm_aov <- anova(nm_fit)
print(nm_aov)




#alternatively could do this
alt_aov <- aov(net_min ~ incubation * farm, data = data)
summary(alt_aov)


#post-hoc testing
nm_tukey <- TukeyHSD(alt_aov, 'incubation:farm', conf.level = 0.95)
print(nm_tukey)
```

Plotting Min/Immob
```{r}
library('interactions')
library('ggplot2')




nm_plot <- cat_plot(nm_fit, pred = farm, modx = incubation, 
         plot.points = TRUE, 
         data = data, 
         jitter = 0,
         errorbar.width = 0.3,
         x.label = c('Farm Management Type'),
         y.label = c('μg N per day'),
         main.title = c('Net Nitrogen Mineralization Rate'),
         legend.main = c('Incubation Type')
         )
nm_plot + theme(plot.title = element_text(hjust = 0.5))

ggsave("nmin_plot.jpeg")
```



For nitrification
```{r}


#one-way farm
nit_fit1 <- lm(net_nit ~ farm, data = data)

#two-way farm and incubation
nit_fit2 <- lm(net_nit ~ incubation + farm, data = data)
#interaction
nit_fit <- lm(net_nit ~ incubation * farm, data = data)
summary(nit_fit)

library(AICcmodavg)
model.set <- list(nm_fit1, nm_fit2, nm_fit)
model.names <- c("one", "two", "interaction")
aictab(model.set, modnames = model.names)
#interaction has lowest AIC score and is the best fit for the data.

#check for homoscedasticity
par(mfrow = c(2,2))
plot(nit_fit)
par(mfrow=c(1,1))



naov <- anova(nit_fit)
print(naov)

#alternatively could do this
alt_aov2 <- aov(net_nit ~ incubation * farm, data = data)
summary(alt_aov2)

#post-hoc testing

nitInt_tukey <- TukeyHSD(alt_aov2, 'incubation:farm', conf.level = 0.95)
print(nitInt_tukey)


```

```{r}

nit_plot <- cat_plot(nit_fit, pred = farm, modx = incubation, 
         plot.points = TRUE, 
         data = data, 
         jitter = 0,
         errorbar.width = 0.3,
         x.label = c('Farm Management Type'),
         y.label = c('μg N per day'),
         main.title = c('Net Nitrification Rate'),
         legend.main = c('Incubation Type')
         )

nit_plot + theme(plot.title = element_text(hjust = 0.5))

ggsave("nit_plot.jpeg")

```

